apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
          # - key: eshwar
          #   operator: In
          #   values:
          #   - dev
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon
      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
